export const COUNTRY_LIST = [
  { label: "Afghanistan", code: "AF", dialingCode: "+93" },
  { label: "Åland Islands", code: "AX", dialingCode: "+358" },
  { label: "Albania", code: "AL", dialingCode: "+355" },
  { label: "Algeria", code: "DZ", dialingCode: "+213" },
  { label: "Andorra", code: "AD", dialingCode: "+376" },
  { label: "Angola", code: "AO", dialingCode: "+244" },
  { label: "Antarctica", code: "AQ", dialingCode: "+672" },
  { label: "Argentina", code: "AR", dialingCode: "+54" },
  { label: "Armenia", code: "AM", dialingCode: "+374" },
  { label: "Aruba", code: "AW", dialingCode: "+297" },
  { label: "Australia", code: "AU", dialingCode: "+61" },
  { label: "Austria", code: "AT", dialingCode: "+43" },
  { label: "Azerbaijan", code: "AZ", dialingCode: "+994" },
  { label: "Bahrain", code: "BH", dialingCode: "+973" },
  { label: "Bangladesh", code: "BD", dialingCode: "+880" },
  { label: "Belarus", code: "BY", dialingCode: "+375" },
  { label: "Belgium", code: "BE", dialingCode: "+32" },
  { label: "Belize", code: "BZ", dialingCode: "+501" },
  { label: "Benin", code: "BJ", dialingCode: "+229" },
  { label: "Bhutan", code: "BT", dialingCode: "+975" },
  { label: "Bolivia", code: "BO", dialingCode: "+591" },
  { label: "Bosnia and Herzegovina", code: "BA", dialingCode: "+387" },
  { label: "Botswana", code: "BW", dialingCode: "+267" },
  { label: "Brazil", code: "BR", dialingCode: "+55" },
  { label: "Brunei Darussalam", code: "BN", dialingCode: "+673" },
  { label: "Bulgaria", code: "BG", dialingCode: "+359" },
  { label: "Burkina Faso", code: "BF", dialingCode: "+226" },
  { label: "Burundi", code: "BI", dialingCode: "+257" },
  { label: "Cambodia", code: "KH", dialingCode: "+855" },
  { label: "Cameroon", code: "CM", dialingCode: "+237" },
  { label: "Canada", code: "CA", dialingCode: "+1" },
  { label: "Cape Verde", code: "CV", dialingCode: "+238" },
  { label: "Central African Republic", code: "CF", dialingCode: "+236" },
  { label: "Chad", code: "TD", dialingCode: "+235" },
  { label: "Chile", code: "CL", dialingCode: "+56" },
  { label: "China", code: "CN", dialingCode: "+86" },
  { label: "Christmas Island", code: "CX", dialingCode: "+61" },
  { label: "Cocos (Keeling) Islands", code: "CC", dialingCode: "+61" },
  { label: "Colombia", code: "CO", dialingCode: "+57" },
  { label: "Comoros", code: "KM", dialingCode: "+269" },
  { label: "Congo", code: "CG", dialingCode: "+242" },
  { label: "Cook Islands", code: "CK", dialingCode: "+682" },
  { label: "Costa Rica", code: "CR", dialingCode: "+506" },
  { label: "Cote D'Ivoire", code: "CI", dialingCode: "+225" },
  { label: "Croatia", code: "HR", dialingCode: "+385" },
  { label: "Cuba", code: "CU", dialingCode: "+53" },
  { label: "Cyprus", code: "CY", dialingCode: "+357" },
  { label: "Czech Republic", code: "CZ", dialingCode: "+420" },
  { label: "Denmark", code: "DK", dialingCode: "+45" },
  { label: "Djibouti", code: "DJ", dialingCode: "+253" },
  { label: "Ecuador", code: "EC", dialingCode: "+593" },
  { label: "Egypt", code: "EG", dialingCode: "+20" },
  { label: "El Salvador", code: "SV", dialingCode: "+503" },
  { label: "Equatorial Guinea", code: "GQ", dialingCode: "+240" },
  { label: "Eritrea", code: "ER", dialingCode: "+291" },
  { label: "Estonia", code: "EE", dialingCode: "+372" },
  { label: "Ethiopia", code: "ET", dialingCode: "+251" },
  { label: "Falkland Islands (Malvinas)", code: "FK", dialingCode: "+500" },
  { label: "Faroe Islands", code: "FO", dialingCode: "+298" },
  { label: "Fiji", code: "FJ", dialingCode: "+679" },
  { label: "Finland", code: "FI", dialingCode: "+358" },
  { label: "France", code: "FR", dialingCode: "+33" },
  { label: "French Guiana", code: "GF", dialingCode: "+594" },
  { label: "French Polynesia", code: "PF", dialingCode: "+689" },
  { label: "Gabon", code: "GA", dialingCode: "+241" },
  { label: "Gambia", code: "GM", dialingCode: "+220" },
  { label: "Georgia", code: "GE", dialingCode: "+995" },
  { label: "Germany", code: "DE", dialingCode: "+49" },
  { label: "Ghana", code: "GH", dialingCode: "+233" },
  { label: "Gibraltar", code: "GI", dialingCode: "+350" },
  { label: "Greece", code: "GR", dialingCode: "+30" },
  { label: "Greenland", code: "GL", dialingCode: "+299" },
  { label: "Guadeloupe", code: "GP", dialingCode: "+590" },
  { label: "Guatemala", code: "GT", dialingCode: "+502" },
  { label: "Guernsey", code: "GG", dialingCode: "+44" },
  { label: "Guinea", code: "GN", dialingCode: "+224" },
  { label: "Guinea-Bissau", code: "GW", dialingCode: "+245" },
  { label: "Guyana", code: "GY", dialingCode: "+592" },
  { label: "Haiti", code: "HT", dialingCode: "+509" },
  { label: "Honduras", code: "HN", dialingCode: "+504" },
  { label: "Hong Kong", code: "HK", dialingCode: "+852" },
  { label: "Hungary", code: "HU", dialingCode: "+36" },
  { label: "Iceland", code: "IS", dialingCode: "+354" },
  { label: "India", code: "IN", dialingCode: "+91" },
  { label: "Indonesia", code: "ID", dialingCode: "+62" },
  { label: "Iran", code: "IR", dialingCode: "+98" },
  { label: "Iraq", code: "IQ", dialingCode: "+964" },
  { label: "Ireland", code: "IE", dialingCode: "+353" },
  { label: "Isle of Man", code: "IM", dialingCode: "+44" },
  { label: "Israel", code: "IL", dialingCode: "+972" },
  { label: "Italy", code: "IT", dialingCode: "+39" },
  { label: "Japan", code: "JP", dialingCode: "+81" },
  { label: "Jersey", code: "JE", dialingCode: "+44" },
  { label: "Jordan", code: "JO", dialingCode: "+962" },
  { label: "Kazakhstan", code: "KZ", dialingCode: "+7" },
  { label: "Kenya", code: "KE", dialingCode: "+254" },
  { label: "Kiribati", code: "KI", dialingCode: "+686" },
  { label: "Kuwait", code: "KW", dialingCode: "+965" },
  { label: "Kyrgyzstan", code: "KG", dialingCode: "+996" },
  { label: "Laos", code: "LA", dialingCode: "+856" },
  { label: "Latvia", code: "LV", dialingCode: "+371" },
  { label: "Lebanon", code: "LB", dialingCode: "+961" },
  { label: "Lesotho", code: "LS", dialingCode: "+266" },
  { label: "Liberia", code: "LR", dialingCode: "+231" },
  { label: "Libya", code: "LY", dialingCode: "+218" },
  { label: "Liechtenstein", code: "LI", dialingCode: "+423" },
  { label: "Lithuania", code: "LT", dialingCode: "+370" },
  { label: "Luxembourg", code: "LU", dialingCode: "+352" },
  { label: "Macau", code: "MO", dialingCode: "+853" },
  { label: "Madagascar", code: "MG", dialingCode: "+261" },
  { label: "Malawi", code: "MW", dialingCode: "+265" },
  { label: "Malaysia", code: "MY", dialingCode: "+60" },
  { label: "Maldives", code: "MV", dialingCode: "+960" },
  { label: "Mali", code: "ML", dialingCode: "+223" },
  { label: "Malta", code: "MT", dialingCode: "+356" },
  { label: "Marshall Islands", code: "MH", dialingCode: "+692" },
  { label: "Martinique", code: "MQ", dialingCode: "+596" },
  { label: "Mauritania", code: "MR", dialingCode: "+222" },
  { label: "Mauritius", code: "MU", dialingCode: "+230" },
  { label: "Mexico", code: "MX", dialingCode: "+52" },
  { label: "Micronesia", code: "FM", dialingCode: "+691" },
  { label: "Moldova", code: "MD", dialingCode: "+373" },
  { label: "Monaco", code: "MC", dialingCode: "+377" },
  { label: "Mongolia", code: "MN", dialingCode: "+976" },
  { label: "Montenegro", code: "ME", dialingCode: "+382" },
  { label: "Morocco", code: "MA", dialingCode: "+212" },
  { label: "Mozambique", code: "MZ", dialingCode: "+258" },
  { label: "Myanmar", code: "MM", dialingCode: "+95" },
  { label: "Namibia", code: "NA", dialingCode: "+264" },
  { label: "Nauru", code: "NR", dialingCode: "+674" },
  { label: "Nepal", code: "NP", dialingCode: "+977" },
  { label: "Netherlands", code: "NL", dialingCode: "+31" },
  { label: "New Zealand", code: "NZ", dialingCode: "+64" },
  { label: "Nicaragua", code: "NI", dialingCode: "+505" },
  { label: "Niger", code: "NE", dialingCode: "+227" },
  { label: "Nigeria", code: "NG", dialingCode: "+234" },
  { label: "Niue", code: "NU", dialingCode: "+683" },
  { label: "Norfolk Island", code: "NF", dialingCode: "+672" },
  { label: "North Korea", code: "KP", dialingCode: "+850" },
  { label: "North Macedonia", code: "MK", dialingCode: "+389" },
  { label: "Norway", code: "NO", dialingCode: "+47" },
  { label: "Oman", code: "OM", dialingCode: "+968" },
  { label: "Pakistan", code: "PK", dialingCode: "+92" },
  { label: "Palau", code: "PW", dialingCode: "+680" },
  { label: "Palestine", code: "PS", dialingCode: "+970" },
  { label: "Panama", code: "PA", dialingCode: "+507" },
  { label: "Papua New Guinea", code: "PG", dialingCode: "+675" },
  { label: "Paraguay", code: "PY", dialingCode: "+595" },
  { label: "Peru", code: "PE", dialingCode: "+51" },
  { label: "Philippines", code: "PH", dialingCode: "+63" },
  { label: "Poland", code: "PL", dialingCode: "+48" },
  { label: "Portugal", code: "PT", dialingCode: "+351" },
  { label: "Puerto Rico", code: "PR", dialingCode: "+1" },
  { label: "Qatar", code: "QA", dialingCode: "+974" },
  { label: "Romania", code: "RO", dialingCode: "+40" },
  { label: "Russia", code: "RU", dialingCode: "+7" },
  { label: "Rwanda", code: "RW", dialingCode: "+250" },
  { label: "Samoa", code: "WS", dialingCode: "+685" },
  { label: "San Marino", code: "SM", dialingCode: "+378" },
  { label: "Sao Tome and Principe", code: "ST", dialingCode: "+239" },
  { label: "Saudi Arabia", code: "SA", dialingCode: "+966" },
  { label: "Senegal", code: "SN", dialingCode: "+221" },
  { label: "Serbia", code: "RS", dialingCode: "+381" },
  { label: "Seychelles", code: "SC", dialingCode: "+248" },
  { label: "Sierra Leone", code: "SL", dialingCode: "+232" },
  { label: "Singapore", code: "SG", dialingCode: "+65" },
  { label: "Slovakia", code: "SK", dialingCode: "+421" },
  { label: "Slovenia", code: "SI", dialingCode: "+386" },
  { label: "Solomon Islands", code: "SB", dialingCode: "+677" },
  { label: "Somalia", code: "SO", dialingCode: "+252" },
  { label: "South Africa", code: "ZA", dialingCode: "+27" },
  { label: "South Korea", code: "KR", dialingCode: "+82" },
  { label: "South Sudan", code: "SS", dialingCode: "+211" },
  { label: "Spain", code: "ES", dialingCode: "+34" },
  { label: "Sri Lanka", code: "LK", dialingCode: "+94" },
  { label: "Sudan", code: "SD", dialingCode: "+249" },
  { label: "Suriname", code: "SR", dialingCode: "+597" },
  { label: "Swaziland", code: "SZ", dialingCode: "+268" },
  { label: "Sweden", code: "SE", dialingCode: "+46" },
  { label: "Switzerland", code: "CH", dialingCode: "+41" },
  { label: "Syria", code: "SY", dialingCode: "+963" },
  { label: "Taiwan", code: "TW", dialingCode: "+886" },
  { label: "Tajikistan", code: "TJ", dialingCode: "+992" },
  { label: "Tanzania", code: "TZ", dialingCode: "+255" },
  { label: "Thailand", code: "TH", dialingCode: "+66" },
  { label: "Timor-Leste", code: "TL", dialingCode: "+670" },
  { label: "Togo", code: "TG", dialingCode: "+228" },
  { label: "Tonga", code: "TO", dialingCode: "+676" },
  { label: "Tunisia", code: "TN", dialingCode: "+216" },
  { label: "Turkey", code: "TR", dialingCode: "+90" },
  { label: "Turkmenistan", code: "TM", dialingCode: "+993" },
  { label: "Tuvalu", code: "TV", dialingCode: "+688" },
  { label: "Uganda", code: "UG", dialingCode: "+256" },
  { label: "Ukraine", code: "UA", dialingCode: "+380" },
  { label: "United Arab Emirates", code: "AE", dialingCode: "+971" },
  { label: "United Kingdom", code: "GB", dialingCode: "+44" },
  { label: "United States", code: "US", dialingCode: "+1" },
  { label: "Uruguay", code: "UY", dialingCode: "+598" },
  { label: "Uzbekistan", code: "UZ", dialingCode: "+998" },
  { label: "Vanuatu", code: "VU", dialingCode: "+678" },
  { label: "Vatican City", code: "VA", dialingCode: "+379" },
  { label: "Venezuela", code: "VE", dialingCode: "+58" },
  { label: "Vietnam", code: "VN", dialingCode: "+84" },
  { label: "Yemen", code: "YE", dialingCode: "+967" },
  { label: "Zambia", code: "ZM", dialingCode: "+260" },
  { label: "Zimbabwe", code: "ZW", dialingCode: "+263" },
];
